### PR TITLE
allow getting token from the google internal metadata server

### PR DESCRIPTION
**Pull request by kenan-gillet**

### CODE REVIEW

**Comment by kenan-gillet** [comment]
let me know if you want me to create some individual PR, thanks

**Comment by nlfiedler** [comment]
Terrific, thank you!

**Comment by kenan-gillet** [comment]
excellent, would you mind tagging it? thanks

**Comment by nlfiedler** [comment]
Good idea, I've tagged 0.3.1.

**Comment by kenan-gillet** [comment]
Great, thanks

**Pull request merged**
